version: '2'
services:
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=devcode
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - laravel-mysql-db:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 15s
      retries: 10
  backend-api-service: 
    image: collaborative-core-laravel
    restart: always
    ports:
      - 8080:3030
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  laravel-mysql-db:
    driver: local
